pnpm-lock.yaml
sites/credit/package.json
sites/credit/src/siteDef.ts
sites/market/package.json
sites/market/src/siteDef.ts

see comments in ui repo for 0.3.0

Changes to SiteDef from ui@0.3.0

---

sites/credit/src/app/api/auth/login/route.ts
sites/credit/src/app/api/auth/logout/route.ts
sites/credit/src/content/slides/compare-table.tsx
sites/credit/src/content/slides/direct-ownership.tsx
sites/credit/src/content/slides/easy-spending.tsx
sites/credit/src/content/slides/flexible-borrowing.tsx
sites/credit/src/content/slides/new-1-percent/index.tsx

Credit,  fix: added api routes for login/logout
added 'add=true' to content buy links

Credit, fix: added api routes for login/logout

---

pnpm-lock.yaml
sites/credit/package.json
sites/credit/src/app/buy/card-detail.tsx
sites/credit/src/app/buy/page.tsx
sites/credit/src/content/slides/direct-ownership.tsx

fix: missing hidden peerDep 'request'
fix: /buy - missing radios for prod choices near image
fix: wrong poster fn for fireworks video

Credit: fix: /buy - missing radios for prod choices; /buy - enh responsivity

---

sites/network/src/content/slides/power-in-your-hands.tsx
sites/network/src/content/slides/run-the-network.ts

Updated links in network hero slide

---

package.json
packages/common/components/header/mobile-bag-drawer.tsx
packages/common/package.json
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/exchange/package.json
sites/finance/package.json
sites/market/package.json
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/partners/package.json

Requires https://github.com/hanzoai/react-sdk/pull/64 to be accepted.

Common: Changed mobile bag from Sheet to div

---

packages/common/components/root-layout.tsx
packages/common/components/scripts.tsx
packages/common/style/lux-global.css

Body will be hidden until the scripts are loaded on client side.

Common: Fix loading screen before styles are loaded

---

packages/common/components/header/desktop-bag-popup.tsx
packages/common/components/header/mobile-bag-drawer.tsx

Added checkoutOpen and bagOpen states to desktop and mobile bag drawer

Common: Moved checkout open state from hanzo/commerce to hanzo/common bag drawer

---

package.json
packages/common/components/header/desktop-bag-popup.tsx
packages/common/components/header/mobile-bag-drawer.tsx
packages/common/components/scripts.tsx
packages/common/next/analytics/fpixel.ts
packages/common/next/analytics/google-analytics.ts
packages/common/next/analytics/index.ts
packages/common/package.json
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/exchange/package.json
sites/finance/package.json
sites/market/package.json
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/partners/package.json

GA4 events:
- login 
- purchase 
- add_payment_info 
- add_shipping_info 
- add_to_cart 
- begin_checkout 
- purchase 
- remove_from_cart 
- view_cart 
Meta Pixel events:
- AddPaymentInfo
- AddToCart
- InitiateCheckout
- Purchase
requires bump of hanzo/common

Common: send analytics events to GA4 and Pixel

---

package.json
packages/common/components/commerce/checkout-panel/dt-checkout-panel.tsx
packages/common/components/commerce/checkout-panel/index.tsx
packages/common/components/commerce/desktop-bag-popup.tsx
packages/common/package.json
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/credit/src/components/compare-cards/rows-content.tsx
sites/credit/src/components/compare-cards/select-card-row/card-hero.tsx
sites/exchange/package.json
sites/finance/package.json
sites/finance/src/app/layout.tsx
sites/login/package.json
sites/market/package.json
sites/market/src/content/products/gold/index.tsx
sites/market/src/content/products/silver/index.tsx
sites/market/src/util.ts
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/partners/package.json
sites/quest/package.json
sites/shop/package.json
sites/shop/src/content/products/gold/index.tsx
sites/shop/src/content/products/silver/index.tsx
sites/shop/src/util.ts

Requires https://github.com/hanzoai/react-sdk/pull/77
Requires bump of hanzo/common

Common: Enable promo codes and shipping on checkout

---

package.json
packages/common/package.json
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/exchange/package.json
sites/finance/package.json
sites/login/package.json
sites/market/package.json
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/partners/package.json
sites/quest/package.json
sites/shop/package.json
utilities/market-data-generator/package.json

Fix for drawer / carousel gesture interaction

---

package.json
packages/common/components/chat-widget.tsx
packages/common/components/commerce/bag-button.tsx
packages/common/components/commerce/desktop-bag-popup.tsx
packages/common/components/commerce/mobile-bag-drawer.tsx
packages/common/components/header/desktop.tsx
packages/common/components/header/mobile.tsx
packages/common/package.json
packages/common/style/lux-colors.css
please-keep.txt
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/exchange/package.json
sites/finance/package.json
sites/login/package.json
sites/market/package.json
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/network/src/app/page.tsx
sites/network/src/content/slides/power-in-your-hands.tsx
sites/partners/package.json
sites/quest/package.json
sites/shop/package.json
utilities/market-data-generator/package.json

z - index / overlay fixes and improvements in common modules

---

package.json
packages/common/components/root-layout.tsx
packages/common/package.json
pnpm-lock.yaml
sites/blank/package.json
sites/credit/package.json
sites/credit/src/components/reviews-carousel.tsx
sites/exchange/package.json
sites/finance/package.json
sites/login/package.json
sites/market/package.json
sites/network-safe/package.json
sites/network-wallet/package.json
sites/network/package.json
sites/partners/package.json
sites/quest/package.json
sites/shop/package.json
utilities/market-data-generator/package.json

removed 'overflow: hidden' from body tag; version bumps

---

sites/credit/src/app/cards/[slug]/page.tsx
sites/credit/src/components/view-card-details/benefits.tsx
sites/credit/src/components/view-card-details/cards-bar.tsx
sites/credit/src/components/view-card-details/desktop.tsx
sites/credit/src/components/view-card-details/mobile.tsx
sites/credit/src/components/view-card-details/tablet.tsx

- Added cards bar on card details page
- Detect layout on resize for card details page (avoids unnecessary spline animations render)
- Fixed benefits height bug on iOS

Credit: Enh card details page

---

sites/credit/src/components/cards-carousel.tsx
sites/credit/src/content/slides/browse-cards.tsx

Requires https://github.com/hanzoai/react-sdk/pull/85 to show the browser carousel full width on desktop

Credit: Added all cards to browse cards carousel

---

packages/common/components/auth/login-panel.tsx
packages/common/components/footer.tsx
packages/common/components/header/desktop.tsx
packages/common/components/header/mobile.tsx
packages/common/components/logo.tsx
packages/common/site-def/footer/ecosystem.ts
packages/common/site-def/footer/network.ts
sites/credit/src/content/commerce/families/cn.ts
sites/market/src/content/commerce/families/cn.ts
sites/network/src/app/[slug]/page.tsx
sites/network/src/app/page.tsx
sites/network/src/blocks/components/product-detail-block.tsx
sites/network/src/blocks/def/product-detail-block.ts
sites/network/src/components/product-cta.tsx
sites/network/src/content/commerce/families/cn.ts
sites/network/src/content/index.ts
sites/network/src/content/products/coin/accordian/index.tsx
sites/network/src/content/products/coin/accordian/lux-coin-tokenomics.mdx
sites/network/src/content/products/coin/index.tsx
sites/network/src/content/products/coin/video.ts
sites/network/src/content/products/validator/accordian/index.tsx
sites/network/src/content/products/validator/accordian/run-a-node.mdx
sites/network/src/content/products/validator/accordian/scarce-and-appreciable-asset.mdx
sites/network/src/content/products/validator/index.tsx
sites/network/src/content/products/validator/video.ts
sites/network/src/content/slides/run-the-network-cards.tsx
sites/network/src/content/slides/wagmi.tsx
sites/shop/src/app/[slug]/page.tsx
sites/shop/src/content/commerce/families/cn.ts

- Footer and header style and content changes
- Added coin and validator pages on network
- Updated coin prices
requires bump of @luxdefi/common

Common, Credit, Market, Network, Shop: Style and content changes

---

packages/common/components/auth/login-panel.tsx
packages/common/package.json
pnpm-lock.yaml
sites/credit/src/app/login/page.tsx
sites/exchange/src/app/login/page.tsx
sites/finance/src/app/login/page.tsx
sites/login/src/app/login/page.tsx
sites/market/src/app/login/page.tsx
sites/network-safe/src/app/login/page.tsx
sites/network-wallet/src/app/login/page.tsx
sites/network/src/app/login/page.tsx
sites/shop/src/app/login/page.tsx

`reviews` array could be moved to each sites content folder, however login pages are going away with https://github.com/luxfi/web/issues/161 so I'd leave it like this for now
requires bump of luxdefi/common

Common: Fix login panel layout and reviews carousel

---

packages/common/components/auth/login-panel.tsx
packages/common/site-def/footer/legal.ts

requires bump of @luxdefi/common

Common: fixed terms links

---

packages/core/components/commerce/checkout-panel/close-button.tsx
packages/core/components/commerce/checkout-panel/dt-checkout-panel.tsx
packages/core/components/commerce/checkout-panel/index.tsx
packages/core/components/commerce/checkout-panel/links-row.tsx
packages/core/components/commerce/checkout-panel/mb-checkout-panel.tsx
packages/core/components/commerce/desktop-bag-popup.tsx
packages/core/components/commerce/mobile-bag-drawer.tsx
sites/credit/src/app/checkout/layout.tsx
sites/credit/src/app/checkout/page.tsx
sites/market/src/app/checkout/page.tsx
sites/network/src/app/checkout/page.tsx
sites/shop/src/app/checkout/page.tsx

Common: Changed checkout layout

---

sites/credit/src/components/cards-carousel-browse.tsx
sites/credit/src/content/cards/black/index.tsx
sites/credit/src/content/cards/elite/index.tsx
sites/credit/src/content/cards/founder/index.tsx
sites/credit/src/content/cards/sovereign/index.tsx
sites/credit/src/content/index.ts
sites/credit/src/content/slides/auto-repayment.tsx
sites/credit/src/content/slides/browse-cards.tsx
sites/credit/src/content/slides/hero/index.tsx

Fix: Changed subheading on multi-card window ('Choose Your Card' slide)
Also, changed the link of the 'Buy Now' button and 'Black Gunmetal' (Video title) in the 'Auto Loan Repayment' slide

fix issue 214

---

sites/credit/src/app/cards/[slug]/_page/desktop.tsx
sites/credit/src/app/cards/[slug]/_page/mobile.tsx
sites/credit/src/app/cards/[slug]/_page/tablet.tsx
sites/credit/src/content/index.ts

Fix: Made sticky right side bar

fix: Issue/216

---

sites/credit/src/content/index.ts
sites/credit/src/content/slides/compatible.tsx

Fix: Add new section "Compatible With Your LifeStyle" at the Credit Landing Page.

fix issue 217

---

packages/core/components/header/desktop.tsx

Fix: Set nav bar padding value 8px

fix nav bar padding value

---

sites/credit/src/app/page.tsx

Made content max size from 1280px to 1500px in credit landing page ScreenfulBlockComponent

issue/264: card cropped in menu

---

app/bitcoin/package.json
app/blank/package.json
app/cash/package.json
app/cdn/package.json
app/coin/package.json
app/credit/package.json
app/exchange/package.json
app/finance/package.json
app/id/package.json
app/link/package.json
app/market/package.json
app/network/package.json
app/partners/package.json
app/quest/package.json
app/safe/package.json
app/shop/package.json

changed version of ui

---

app/coin/src/layout/home/index.tsx

fix ico issue

---

app/partners/src/content/partners/partners.tsx

Slightly changed the summary so that this will be the newest page, and undo any mistakes that are on the current live.

Forced update
